FROM java:8

VOLUME /tmp

#RUN curl -o app.jar http://10.63.39.117:8081/artifactory/libs-release-local/org/springframework/samples/service/service/microservice-demo/1.1.0.RELEASE/microservice-demo-1.1.0.RELEASE.jar

ADD http://10.63.39.117:8081/artifactory/libs-release-local/org/springframework/samples/service/service/microservice-demo/1.1.0.RELEASE/microservice-demo-1.1.0.RELEASE.jar app.jar


ENTRYPOINT ["java","-Djava.security.egd=file:/dev/./urandom","-jar","/app.jar"]
